imports:
    - { resource: config.yml }

framework:
    router:
        resource: "%kernel.root_dir%/config/routing_dev.yml"
        strict_requirements: true
    profiler: { only_exceptions: false }

web_profiler:
    toolbar: true
    intercept_redirects: false

monolog:
    handlers:
        main:
            type:           rotating_file
            max_files:      3
            path:           "%kernel.logs_dir%/%kernel.environment%.all.log"
            level:          info
            channels:       [!doctrine, !security]
        doctrine:
            type:           stream
            path:           "%kernel.logs_dir%/%kernel.environment%.doctrine.log"
            channels:       doctrine
        authentication:
            type:           rotating_file
            max_files:      15
            path:           "%kernel.logs_dir%/%kernel.environment%.auth.log"
            level:          info
            channels:       mywebsite_user
        main_error:
            type:           fingers_crossed
            action_level:   error
            handler:        streamed_error
        streamed_error:
            type:           rotating_file
            max_files:      15
            path:           "%kernel.logs_dir%/%kernel.environment%.error.log"
            level:          info
        streamed_critical:
            type:           rotating_file
            max_files:      15
            path:           "%kernel.logs_dir%/%kernel.environment%.critical.log"
            level:          critical
        console:
            type:   console
            verbosity_levels:
                VERBOSITY_NORMAL: NOTICE
            formatter: mywebsite_formatter

#swiftmailer:
#    delivery_address: me@example.com

assetic:
    use_controller: true

app:
   payment_organisms:
       default: Paypal
       Be2bill:
           identifier: MYWEBSITE
           password: 123456789
           url: https://secure-test.be2bill.com/front/form/process
       Paypal:
           identifier: mywebsite@mywebsite.com
           password: ~
           url: http://www.sandbox.paypal.com/cgi-bin/webscr

swiftmailer:
    encryption: ssl
    auth_mode:  login
    spool:      { type: memory }

web_profiler_extra:
    routing:
        enabled:        true
        display_in_wdt: true
    container:
        enabled:        true
        display_in_wdt: true
    assetic:
        enabled:        true
        display_in_wdt: true
    twig:
        enabled:        true
        display_in_wdt: true
