parameters:
    mail_blacklist:
        - yopmail.com
        - yopmail.fr
        - yopmail.net
        - cool.fr.nf
        - jetable.fr.nf
        - nospam.ze.tc
        - nomail.xl.cx
        - mega.zik.dj
        - speed.1s.fr
        - courriel.fr.nf
        - moncourrier.fr.nf
        - monemail.fr.nf
        - monmail.fr.nf
        - ypmail.webarnak.fr.eu.org
        - mintemail.com
        - anonymbox.com
        - tempemail.net
        - 10minutemail.com
        - spamgourmet.com
        - mytrashmail.com
        - incognitomail.com
        - mailinator.com
        - spamobox.com
        - mailexpire.com
        - soodonims.com
        - spambox.us
        - nospamfor.us
        - dispostable.com
        - jetable.org
        - spamavert.com
        - meltmail.com
        - trashmail.net
        - trashmail.me
        - trashmail.at
        - trash-mail.at
        - rcpt.at
        - kurzepost.de
        - wegwerfmail.de
        - wegwerfmail.net
        - wegwerfmail.org
        - objectmail.com
        - proxymail.eu
        - email-jetable.fr
        - mail-temporaire.fr
        - mailtemporaire.fr
        - mail-temporaire.com
        - mailtemporaire.com
        - easy-trash-mail.com
        - easytrashmail.com
        - email-jetable.me
        - email-jetable.biz.st
