app_user:
    resource: "@AppUserBundle/Controller/"
    type:     annotation
    prefix:   /

app_portal:
    resource: "@AppPortalBundle/Controller/"
    type:     annotation
    prefix:   /

app_backoffice:
    resource: "@AppAdminBundle/Controller/"
    type:     annotation
    prefix:   /back

app_backuser:
    resource: "@AppBackUserBundle/Controller/"
    type:     annotation
    prefix:   /back

fos_:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"
    prefix:   /back

fos_js_routing:
    resource: "@FOSJsRoutingBundle/Resources/config/routing/routing.xml"

_liip_imagine:
    resource: "@LiipImagineBundle/Resources/config/routing.xml"